name: pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write
  id-token: write
  security-events: write

concurrency:
  group: image-push-${{ github.repository }}
  cancel-in-progress: true

jobs:
  buildx:
    uses: guilhermelinosp/ci-templates/.github/workflows/buildx.yml@latest
    with:
      runner: ubuntu-latest
      registry_owner: ${{ github.repository_owner }}

  release:
    needs: buildx
    uses: guilhermelinosp/ci-templates/.github/workflows/release.yml@latest
    with:
      runner: ubuntu-latest
      registry_owner: ${{ github.repository_owner }}
  push:
    needs: [ release, buildx ]
    uses: guilhermelinosp/ci-templates/.github/workflows/push.yml@latest
    with:
      runner: ubuntu-latest
      registry_owner: ${{ github.repository_owner }}
      image: ${{ needs.buildx.outputs.image }}
      version: ${{ needs.release.outputs.version }}
